<a href="https://colab.research.google.com/github/pxs1990/Data_Science_projects/blob/main/ds_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy:**

# **1. Creating Arrays**

In [2]:
import numpy as np

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
np.arange(10) # 0..9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 1, 5)         # 5 numbers evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,3)

array([[0.34020318, 0.58913062, 0.36886086],
       [0.9106811 , 0.17880807, 0.82139749],
       [0.50591461, 0.015878  , 0.4525879 ]])

In [ ]:
np.random.randint(0, 10, 5)

array([3, 5, 7, 2, 1])

# **2. Array Attributes**

In [ ]:
arr=np.ones((2,2))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 2)
4
float64

# **3. Reshaping Arrays**

In [ ]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2 = arr.reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [ ]:
flat = arr2.flatten() # copy of original
print(flat)

[0 1 2 3 4 5 6 7 8]

In [ ]:
rav = arr2.ravel() # not a copy. change here changes original too.
print(rav)

[0 1 2 3 4 5 6 7 8]

In [ ]:
print(arr2.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]

# **4. Indexing & Slicing**

In [ ]:
arr[0]
arr[1:4]
arr[:, 0]
arr[1:3, 2:4]
arr[arr > 5] # boolean filter
df["high_salary"] = np.where(df["salary"] > 50000, 1, 0)

# **5. Math Operations**

In [ ]:
np.add(a, b)
np.subtract(a, b)
np.multiply(a, b)
np.divide(a, b)
np.power(a, 2)

np.sqrt(arr)
np.exp(arr)
np.log(arr)

# **6. Aggregations**

In [ ]:
np.sum(arr)
np.mean(arr)
np.std(arr)
np.var(arr)
np.min(arr)
np.max(arr)
np.argmin(arr) # index of max val
np.argmax(arr)
np.cumsum(arr) # cumulative sum

# **7. Broadcasting**

In [ ]:
arr = np.array([1, 2, 3])
print(arr + 5)
print(arr + [1,2,3])
print(arr * [1,2,3])

[6 7 8]
[2 4 6]
[1 4 9]

# **8. Stacking & Concatenation**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate([a, b]) # joins along an existing array

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.concatenate([a, b]) # default axis=0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.concatenate([a, b],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

# **9. Sorting & Unique**

In [ ]:
arr = np.array([5, 1, 4, 2])

arr1=np.sort(arr)
print(arr1)
# np.sort(arr)[::-1] for descending order

[1 2 4 5]

In [ ]:
np.argsort(arr) # index that would sort the arr

array([1, 3, 2, 0])

In [ ]:
np.unique(arr) # removes duplicates

array([1, 2, 4, 5])

# **10. Linear Algebra**

In [ ]:
np.dot(a, b)
np.matmul(a, b)
np.linalg.inv(A)
np.linalg.det(A)
np.linalg.eig(A)

# **11. Random Module**

In [ ]:
np.random.seed(42) # reproducibility

In [ ]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [ ]:
np.random.randn(3)

array([-1.11188012,  0.31890218,  0.27904129])

In [ ]:
np.random.randint(0, 10, 5)

array([7, 2, 5, 4, 1])

In [4]:
arr=np.arange(10)
np.random.choice(arr)

np.int64(3)

In [7]:
import random
sampled_list = random.sample([7, 2, 5, 4, 1], 3)
sampled_list

[2, 1, 7]

In [ ]:
df_sample = df.sample(frac=0.4, random_state=42).sort_index()

## **Panda**

# **1. Creating  DataFrames**

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [20, 30, 40]
})
df

  name  age
0    A   20
1    B   30
2    C   40

In [ ]:
# from list of iterables
data = [
    [1, "Alice"],
    [2, "Bob"],
    [3, "Charlie"]
]

df = pd.DataFrame(data, columns=["id", "name"])
df

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie

# **2. Reading & Writing Data**

In [ ]:
# Read
df = pd.read_csv("file.csv")          # read CSV
df = pd.read_excel("file.xlsx")       # read Excel

# Write
df.to_csv("output.csv", index=False)
df.to_excel("output.xlsx", index=False)

In [ ]:
import snowflake.connector

# Connect to Snowflake
connector = snowflake.connector.connect(
    user="YOUR_USER",
    password="YOUR_PASSWORD",
    account="YOUR_ACCOUNT",         # e.g. abcde-xy12345
    warehouse="COMPUTE_WH",
    database="MY_DB",
    schema="PUBLIC"
)

# Query Snowflake
query = "SELECT * FROM my_table;"

# Read into DataFrame
df = pd.read_sql(query, connector)

# **3. Quick Inspection**

In [ ]:
df.head()         # first 5 rows
df.tail(3)        # last 3 rows
df.info()         # dtypes + non-null count
df.describe()     # summary stats (numeric)
df.shape          # (rows, columns)
df.columns        # column names
df.dtypes         # data types

# **4. Selecting Columns & Rows**

In [ ]:
df["name"]                  # single column (Series)
df[["name", "salary"]]      # multiple columns (DataFrame)

#loc (label-based)
df.loc[0, "name"]                 # row index 0, column "name"
df.loc[0:2, ["name", "age"]]      # rows 0 to 2, selected columns
df.loc[df["city"] == "NY", :]     # rows where city == "NY"

#iloc (index-based)
df.iloc[0, 0]          # first row, first column
df.iloc[0:2, 1:3]      # rows 0-1, cols 1-2

# **5. Filtering Rows (Boolean Indexing)**

In [ ]:
# age > 30
df[df["age"] > 30]

# multiple conditions: ( ) & ( )
df[(df["age"] > 25) & (df["city"] == "NY")]

df[df["city"].isin(["NY", "LA"])]
df[df["age"].between(20, 30, inclusive="left")]
df[df["name"].str.contains("an", case=False, na=False)]
df[df["city"].str.startswith("N")]
df[df["city"].str.endswith("A")]
df[df.duplicated(["name", "year"], keep=False)]
df[~df.duplicated("email")]
df[df["age"] > 30] => df.loc[df["age"] > 30] => df.loc[lambda x: x["age"] > 30]

# **6. Adding, Modifying, Dropping Columns**

In [ ]:
# Add / Modify col
df["age_plus_10"] = df["age"] + 10
df["is_ny"] = df["city"] == "NY"

# Drop columns
df = df.drop(columns=["age_plus_10"])
# or
df = df.drop(["age_plus_10"], axis=1)

# **7. Handling Missing Data**

In [ ]:
#Check nan
df2.isna()          # True/False mask
df2.isna().sum()    # missing count per column

#Drop rows with missing
df2.dropna()                     # drop any row with NaN
df2.dropna(subset=["salary"])    # drop rows where salary is NaN

#Fill nan
df2["salary"] = df2["salary"].fillna(df2["salary"].mean())
df2["city"] = df2["city"].fillna("Unknown")

# **8. Dtypes & Conversions (astype, to_numeric, dates)**

In [ ]:
df["age"] = df["age"].astype("int64")       # change dtype

# Coerce bad values to NaN
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")

In [ ]:
#Datetime
df_dates = pd.DataFrame({
    "date": ["2025-01-01", "2025-01-02", "2025-01-03"],
    "value": [10, 20, 15]
})

df_dates["date"] = pd.to_datetime(df_dates["date"])
df_dates.set_index("date", inplace=True)

# Resample by month and sum
df_dates.resample("M").sum()

/tmp/ipython-input-1663977223.py:11: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_dates.resample("M").sum()

            value
date
2025-01-31     45

# **9. Sorting & Ranking**

In [ ]:
df.sort_values("age")                     # ascending
df.sort_values("salary", ascending=False) # descending

df.sort_values(["city", "salary"], ascending=[True, False])

df["salary_rank"] = df["salary"].rank(ascending=False) # new col with rank

# **10. Duplicates**

In [ ]:
# check duplicates
df.duplicated()                     # True/False for duplicate rows
df.duplicated(subset=["name"])      # duplicate by name only

# drop complete duplicates
df_no_dup = df.drop_duplicates()
df_no_dup_name = df.drop_duplicates(subset=["name"], keep="first")

# **11. Groupby**

In [ ]:
# mean salary by city
df.groupby("city")["salary"].mean()

# multiple aggregations
df.groupby("city").agg(
    avg_salary=("salary", "mean"),
    max_age=("age", "max"),
    count=("name", "count")
)

# Group by multiple columns
df.groupby(["city", "age"]).agg(
    total_salary=("salary", "sum")
).reset_index()

# **12. Value Counts**

In [ ]:
# Frequency of each category
df["city"].value_counts()
df["city"].value_counts(normalize=True)  # proportions

# **3. Apply, Map, and Lambda**

If axis=0: function is applied down the rows → each column is passed

If axis=1: function is applied across the columns → each row is passed

In [ ]:
# map for Series
city_map = {"NY": "New York", "LA": "Los Angeles", "CHI": "Chicago"}
df["city_full"] = df["city"].map(city_map)

# column-wise apply (default axis=0)
df[["age", "salary"]].apply(np.mean)

# row-wise apply (axis=1)
def age_salary_ratio(row):
    return row["salary"] / row["age"]

df["salary_per_year"] = df.apply(age_salary_ratio, axis=1)

#apply to a single column(series; axis not needed)
df["age_category"] = df["age"].apply(
    lambda x: "young" if x < 30 else "old"
)

# **14. Merge / Join DataFrames**

In [ ]:
employee_df = pd.DataFrame({
    "emp_id": [1, 2, 3],
    "name": ["Alice", "Bob", "Charlie"]
})

salar_df = pd.DataFrame({
    "emp_id": [1, 2, 4],
    "salary": [50000, 60000, 70000]
})

# Inner join on emp_id
merged = employee_df.merge(salar_df, on="emp_id", how="inner")

# Left join
merged_left = employee_df.merge(salar_df, on="emp_id", how="left")

# **15. Concatenating DataFrames**

In [ ]:
df_top = df.iloc[:2]
df_bottom = df.iloc[2:]

# Row-wise (stack rows)
pd.concat([df_top, df_bottom], axis=0)

# Column-wise (side-by-side)
pd.concat([df[["name", "city"]], df[["age", "salary"]]], axis=1)

# **16. Pivot Tables**

In [ ]:
sales_df = pd.DataFrame({
    "region": ["East", "East", "West", "West"],
    "product": ["A", "B", "A", "B"],
    "sales": [100, 150, 80, 120]
})

pivot = pd.pivot_table(
    data=sales_df,
    index="region",
    columns="product",
    values="sales",
    aggfunc="sum",
    fill_value=0
)
pivot

product    A    B
region
East     100  150
West      80  120

# **17. One-Hot Encoding (get_dummies)**

In [ ]:
df_encoded = pd.get_dummies(sales_df, columns=["region"], drop_first=False)
df_encoded

  product  sales  region_East  region_West
0       A    100         True        False
1       B    150         True        False
2       A     80        False         True
3       B    120        False         True

# **18. Typical flow in a project**

In [ ]:
df = pd.read_csv("data.csv")

# Basic cleaning
df = df.drop(columns="col_name")
df = df.drop_duplicates(subset=["target_col"])
df = df.dropna(subset=["target_col"])

df["date"] = pd.to_datetime(df["date"])

# Feature engineering
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.dayofweek
df["is_weekend"] = df["day_of_week"].isin([5, 6])

# cut col age into bins
df["age_group"] = pd.cut(df["age"], bins=[0, 18, 35, 60, 100], labels=["child", "young", "adult", "senior"])

# Encoding
df = pd.get_dummies(df, columns=["city", "age_group"], drop_first=True)

# Train/test split (then go to sklearn)
from sklearn.model_selection import train_test_split

X = df.drop(columns=["target"])
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **End-to-End model development Script**

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, RandomizedSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay, RocCurveDisplay
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
import joblib
import matplotlib.pyplot as plt

# -----------------------------
# 1) Create a synthetic dataset
# -----------------------------
np.random.seed(42)
n_samples = 2000

# Numeric features
age = np.random.randint(18, 80, size=n_samples)
income = np.random.normal(60000, 15000, size=n_samples)
balance = np.random.normal(2000, 1000, size=n_samples)

# Categorical features
cities = np.random.choice(["Dallas", "Austin", "Houston"], size=n_samples, p=[0.4, 0.3, 0.3])
segment = np.random.choice(["A", "B", "C"], size=n_samples, p=[0.5, 0.3, 0.2])

# Date feature
dates = pd.date_range("2023-01-01", periods=n_samples, freq="D")
signup_date = np.random.choice(dates, size=n_samples)

# Target: probability depends on age, income, segment, etc.
logit = (
    -5
    + 0.03 * (age - 40)          # older → slightly higher risk
    + 0.00003 * (income - 60000) # higher income → lower risk
    + 0.0005 * (balance - 2000)  # more balance → more risk
)
# Segment effect
logit += np.where(segment == "C", 1.0, 0.0)   # segment C more risky
logit += np.where(cities == "Houston", 0.5, 0.0)

prob = 1 / (1 + np.exp(-logit))
y = np.random.binomial(1, prob, size=n_samples)

df = pd.DataFrame({
    "age": age,
    "income": income,
    "balance": balance,
    "city": cities,
    "segment": segment,
    "signup_date": signup_date,
    "default": y,
})

# Introduce some missing values
for col in ["income", "balance"]:
    mask = np.random.rand(n_samples) < 0.05
    df.loc[mask, col] = np.nan

print("Head of raw data:")
print(df.head())
print("\nTarget rate:", df["default"].mean())

# --------------------------------------
# 2) Feature engineering (date features)
# --------------------------------------
df["signup_date"] = pd.to_datetime(df["signup_date"])
df["signup_year"] = df["signup_date"].dt.year
df["signup_month"] = df["signup_date"].dt.month
df["signup_dayofweek"] = df["signup_date"].dt.dayofweek

# IMPORTANT: drop raw date to avoid leakage / complexity
df = df.drop(columns=["signup_date"])

# -------------------
# 3) Train-test split
# -------------------
X = df.drop(columns=["default"])
y = df["default"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTrain size:", X_train.shape, "Test size:", X_test.shape)

# -------------------------------
# 4) Define preprocessing (CT)
# -------------------------------
numeric_features = ["age", "income", "balance", "signup_year", "signup_month", "signup_dayofweek"]
categorical_features = ["city", "segment"]

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# ColumnTransformer applies different preprocessing to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ]
)

# --------------------------------------
# 5) Full pipeline: preprocessing + model
# --------------------------------------
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced_subsample"  # handle some imbalance
)

clf = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", model)
])

# -----------------------------------
# 6) Cross-validation on training set
# -----------------------------------
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_auc = cross_val_score(
    clf,
    X_train,
    y_train,
    cv=cv,
    scoring="roc_auc",
    n_jobs=-1
)

print("\nCV ROC AUC scores:", cv_auc)
print("Mean CV ROC AUC:", cv_auc.mean())

# -------------------------------
# 7) Hyperparameter search (RF)
# -------------------------------
param_distributions = {
    "model__n_estimators": [100, 200, 300],
    "model__max_depth": [None, 5, 10, 20],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2", 0.5],
}

search = RandomizedSearchCV(
    clf,
    param_distributions=param_distributions,
    n_iter=20,
    scoring="roc_auc",
    n_jobs=-1,
    cv=cv,
    random_state=42,
    verbose=1
)

print("\nRunning RandomizedSearchCV...")
search.fit(X_train, y_train)

print("\nBest params:", search.best_params_)
print("Best CV ROC AUC:", search.best_score_)

best_model = search.best_estimator_

# ---------------------------
# 8) Evaluate on test set
# ---------------------------
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

print("\nClassification report (test):")
print(classification_report(y_test, y_pred))

test_auc = roc_auc_score(y_test, y_proba)
print("Test ROC AUC:", test_auc)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion matrix:\n", cm)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Confusion Matrix (Test)")
plt.show()

# ROC curve
RocCurveDisplay.from_predictions(y_test, y_proba)
plt.title("ROC Curve (Test)")
plt.show()

# -------------------------------------------
# 9) Feature importance via permutation
# -------------------------------------------
# Get feature names after preprocessing
ohe = best_model.named_steps["preprocessor"].named_transformers_["cat"].named_steps["onehot"]
cat_feature_names = list(ohe.get_feature_names_out(categorical_features))
all_feature_names = numeric_features + cat_feature_names

print("\nTotal transformed features:", len(all_feature_names))

# Permutation importance on the whole pipeline (safe way)
result = permutation_importance(
    best_model,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42,
    n_jobs=-1
)

importances = pd.Series(result.importances_mean, index=all_feature_names).sort_values(ascending=False)
print("\nTop 10 permutation importances:")
print(importances.head(10))

importances.head(15).plot(kind="barh")
plt.gca().invert_yaxis()
plt.title("Top Feature Importances (Permutation)")
plt.tight_layout()
plt.show()

# -------------------------
# 10) Save the trained model
# -------------------------
joblib.dump(best_model, "rf_default_model.joblib")
print("\nSaved model to rf_default_model.joblib")